spring.datasource.url=jdbc:postgresql://postgresql:5432/webimage
spring.datasource.username=${POSTGRESQL_USER:webimage}
spring.datasource.password=${POSTGRESQL_PASSWORD:webimage}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
